web:
  uploadPath: D:/AtHBPUImage/
spring:
  application:
    name: service
  mail:
    host: smtp.163.com
    username: zhaojunfuyx@163.com
    password: KLHSVSCBXFLDMMRV
    protocol: smtp
    defult-encoding: UTF-8

#  data:
#    mongodb:
#      uri: mongodb://localhost:27017/newsdbmongo
#  redis:
#    host: 127.0.0.1
#    port: 6379
#    jedis:
#      pool:
#        max-active: 8
#        max-wait: -1ms
#        max-idle: 500
#        min-idle: 0
  servlet:
    multipart:
      max-file-size:
        10MB
      max-request-size:
        20MB
  mvc:
    static-path-pattern: /AirLineImage/**
  web:
    resources:
      static-locations: file:${web.uploadPath}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/AtHBPU
    username: AtHBPU
    password: AtHBPU
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-Size: 20
      min-idle: 10
      max-active: 100
      max-wait: 60000
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: news-group
    send-message-timeout: 3000
server:
  port: 8000
eureka:
  client: #将客户端注册到 eureka 服务列表内
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka  #这个地址是 7001注册中心在 application.yml 中暴露出来额注册地址 （单机版）
  instance:
    prefer-ip-address: true  #显示访问路径的 ip 地址
